pod "NAMapKit", :path => "../namapkit.podspec"
pod "pop"

target "DemoTests" do
  pod 'Specta', '~> 0.2.1'
  pod 'Expecta', '~> 0.2.3'
  pod 'FBSnapshotTestCase', '~> 1.1'
  pod 'EXPMatchers+FBSnapshotTest', '~> 1.1.0'
end

